# Generated by Django 2.1.1 on 2018-10-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20181010_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Testing', max_length=50),
        ),
    ]
